version: "3.9"

x-cockroach-image: &cockroach-image
  cockroachdb/cockroach:${CRDB_VERSION:-v25.3.3}

services:
  haproxy:
    image: haproxy:lts
    container_name: haproxy
    ports:
      - "26257:26257"   # SQL
      - "8404:8404"     # HAProxy stats UI
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - crdb-e1a
      - crdb-e1b
      - crdb-w2a
      - crdb-w2b
      - crdb-c1

  # CockroachDB nodes (5 total, 3 regions)
  crdb-e1a:
    image: *cockroach-image
    container_name: crdb-e1a
    command: ["start","--insecure","--listen-addr=0.0.0.0:26257","--advertise-addr=crdb-e1a:26257","--http-addr=0.0.0.0:8080",
              "--locality=region=us-east-1,zone=a","--join=crdb-e1a:26257,crdb-e1b:26257,crdb-w2a:26257,crdb-w2b:26257,crdb-c1:26257"]
    ports:
      - "8080:8080"

  crdb-e1b:
    image: *cockroach-image
    container_name: crdb-e1b
    command: ["start","--insecure","--listen-addr=0.0.0.0:26257","--advertise-addr=crdb-e1b:26257","--http-addr=0.0.0.0:8080",
              "--locality=region=us-east-1,zone=b","--join=crdb-e1a:26257,crdb-e1b:26257,crdb-w2a:26257,crdb-w2b:26257,crdb-c1:26257"]
    ports:
      - "8081:8080"

  crdb-w2a:
    image: *cockroach-image
    container_name: crdb-w2a
    command: ["start","--insecure","--listen-addr=0.0.0.0:26257","--advertise-addr=crdb-w2a:26257","--http-addr=0.0.0.0:8080",
              "--locality=region=us-west-2,zone=a","--join=crdb-e1a:26257,crdb-e1b:26257,crdb-w2a:26257,crdb-w2b:26257,crdb-c1:26257"]
    ports:
      - "8082:8080"

  crdb-w2b:
    image: *cockroach-image
    container_name: crdb-w2b
    command: ["start","--insecure","--listen-addr=0.0.0.0:26257","--advertise-addr=crdb-w2b:26257","--http-addr=0.0.0.0:8080",
              "--locality=region=us-west-2,zone=b","--join=crdb-e1a:26257,crdb-e1b:26257,crdb-w2a:26257,crdb-w2b:26257,crdb-c1:26257"]
    ports:
      - "8083:8080"

  crdb-c1:
    image: *cockroach-image
    container_name: crdb-c1
    command: ["start","--insecure","--listen-addr=0.0.0.0:26257","--advertise-addr=crdb-c1:26257","--http-addr=0.0.0.0:8080",
              "--locality=region=us-central-1,zone=a","--join=crdb-e1a:26257,crdb-e1b:26257,crdb-w2a:26257,crdb-w2b:26257,crdb-c1:26257"]
    ports:
      - "8084:8080"

  # Initialize the cluster once
  crdb-init:
    image: *cockroach-image
    container_name: crdb-init
    depends_on:
      - crdb-e1a
      - crdb-e1b
      - crdb-w2a
      - crdb-w2b
      - crdb-c1
    entrypoint: ["/bin/sh","-c"]
    command: >
      "sleep 4 &&
       /cockroach/cockroach init --insecure --host=crdb-e1a:26257 ||
       true"

  # Bootstrap SQL: locations + demo DB
  crdb-bootstrap:
    image: *cockroach-image
    container_name: crdb-bootstrap
    depends_on:
      - crdb-init
    volumes:
      - ./init.sql:/init.sql:ro
    entrypoint: ["/bin/sh","-c"]
    command: >
      "until /cockroach/cockroach sql --insecure --host=crdb-e1a:26257 -e 'select 1'; do sleep 1; done &&
       /cockroach/cockroach sql --insecure --host=crdb-e1a:26257 --file=/init.sql"

