version: '3.8'

services:

  cockroach-single-node:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - "8080:8080" # default
      - "26257:26257" # default
    stdin_open: true
    tty: true
    container_name: cockroach-single-node
    hostname: cockroach-single-node
